# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do

  before_all do 
    setup_travis
    cocoapods
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "Tomatoro.xcworkspace", scheme: "Tomatoro")
  end

  desc "Run tests and generate code coverage"
  lane :tests do
    run_tests(
      workspace: "Tomatoro.xcworkspace", 
      scheme: "Tomatoro",
      clean: true
    )
  end

  lane :coverage do
    xcov(
      workspace: "Tomatoro.xcworkspace",
      scheme: "Tomatoro",
      output_directory: "./xccov_output"
    )
  end

  lane :beta do
    # Ensure that your git status is not dirty
    ensure_git_status_clean

    # Increment the build number (not the version number)
    # Providing the xcodeproj is optional
    increment_build_number

    # Commit the version bump
    commit_version_bump

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    add_git_tag

    # Push the new commit and tag back to your git remote
    # push_to_git_remote
  end
end
