# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do

  before_all do 
    setup_travis
    cocoapods
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "Tomatoro.xcworkspace", scheme: "Tomatoro")
  end

  desc "Run tests and generate code coverage"
  lane :tests do
    run_tests(
      workspace: "Tomatoro.xcworkspace", 
      scheme: "Tomatoro",
      clean: true
    )
    xcov(
      workspace: "Tomatoro.xcworkspace",
      scheme: "Tomatoro"
    )
    # slather(  
    #   travis: true,  
    #   scheme: "Tomatoro",  
    #   proj: "Tomatoro.xcodeproj",  
    #   workspace: "Tomatoro.xcworkspace"
    # )

  end

end
